### ISSUE TITLE
Inconsistency: Line with code block end tag is higher than without

### ISSUE THREAD

**Issue by SylwesterZarebski** [KhaosCoders/VSCodeBlockEndTag#8]
Line with displayed tag is higher than line with no tag. It is most visible when going to and then out of code block end line when tag is hidden and then redisplayed.
Line height should be the same with or without tag.

Visual Studio 2015 with font Source Code Pro Medium size 9 (non standard font).

**Comment by Khaos66** [comment]
The tag now scales to match any line height with version 1.3

This was a hard one, too.
I didn't really find something on line heights in the editor via Google =/
Found a way though to read the global font size for the editor, so that one is used now.
Ihe issue may still occures, when you use any other extension that manipulates the line height
